### ISSUE TITLE
"Mismatching redirect uri" error when using NSS to log into CSS

### ISSUE THREAD

**Issue by timbl** [nodeSolidServer/node-solid-server#1729]
I get  page with 
```
{"error":"invalid_request","error_description":"Mismatching redirect uri"}
```
and a URI of 

https://inrupt.net/authorize?client_id=e09567c40614847dd3a348683a13666a&redirect_uri=https%3A%2F%2Ftimbl.com%2Ftimbl%2FAutomation%2Ftabbed.ttl%3Fstate%3D391e9862269246f8aad691e854a90155&response_type=code&scope=openid%20offline_access%20webid&state=71ff5784b4a34c87bd4fce74e4607b8c&code_challenge=vl89aeeof4eY30_2kBpvE1lwR6SQlEufQKOgmURoZDQ&code_challenge_method=S256&prompt=none&response_mode=query

when I try to use my NSS-based  inrupt.net to log into timbl.com at

`https://timbl.com/timbl/Automation/tabbed.ttl#this`

I don't see any cookies for local storage in the Apps tab.

In the network tab, I see `400` response with the JSON body

```
{"error":"invalid_request","error_description":"Mismatching redirect uri"}
```

The same thibng happens if i try to load `https://timbl.com/timbl/Automation/tabbed.ttl` without the `#this`

**Comment by timbl** [comment]
I do not have the problem in an incognito browser tab.

**Comment by bourgeoa** [comment]
@timea-solid updated inrupt.net 2 days ago to NSS@5.7.7 this should resolve the issue
You must clean your browser first.

**Comment by mrkvon** [comment]
I just received a report about this error from a person using our app with solidcommunity.net pod. So, it seems it can still appear occasionally.

Do you know what's causing it? Is there anything we can do (e.g. on app level) besides telling people to clear cookies & local storage, or to use browser's private mode?

Clearing local storage/cookies seems like too much to ask folks without technical background... 😕

**Comment by timea-solid** [comment]
This issue is related to https://github.com/inrupt/solid-client-authn-js/issues/2891 and fixed in inrupt/solid-client-authn-js v1.17.2 -> the SolidOS team needs to update it in solid-logic.

**Comment by timea-solid** [comment]
This issue is related to [https://github.com/inrupt/solid-client-authn-js/issues/2891](https://github.com/inrupt/solid-client-authn-js/issues/2891) and fixed in inrupt/solid-client-authn-js v1.17.2 -> the SolidOS team needs to update it in solid-logic.
